### ISSUE TITLE
ClassNotFoundException: scala.collection.GenTraversableOnce

### ISSUE THREAD

**Issue by mnadelson** [spring-cloud/spring-cloud-stream-starters#5]
I am getting a ClassNotFoundException when using the new spring cloud kafka streaming libraries.  I have verified that GenTraversableOnce is in my classpath so I'm not understanding why I'm getting the error.  The stack trace is below and my pom.xml is attached.

org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:874)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at operator.ModeledPositionOperator$.delayedEndpoint$operator$ModeledPositionOperator$1(ModeledPositionOperator.scala:58)
	at operator.ModeledPositionOperator$delayedInit$body.apply(ModeledPositionOperator.scala:57)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at operator.ModeledPositionOperator$.main(ModeledPositionOperator.scala:57)
	at operator.ModeledPositionOperator.main(ModeledPositionOperator.scala)
Caused by: java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
	at kafka.utils.Pool.<init>(Pool.scala:28)
	at kafka.producer.ProducerRequestStatsRegistry$.<init>(ProducerRequestStats.scala:55)
	at kafka.producer.ProducerRequestStatsRegistry$.<clinit>(ProducerRequestStats.scala)
	at kafka.producer.SyncProducer.<init>(SyncProducer.scala:42)
	at kafka.producer.ProducerPool$.createSyncProducer(ProducerPool.scala:38)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:55)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
	at org.springframework.integration.kafka.core.DefaultConnectionFactory.refreshMetadata(DefaultConnectionFactory.java:184)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$3.doWithRetry(KafkaMessageChannelBinder.java:409)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$3.doWithRetry(KafkaMessageChannelBinder.java:405)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:157)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.ensureTopicCreated(KafkaMessageChannelBinder.java:405)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.doBindProducer(KafkaMessageChannelBinder.java:296)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.doBindProducer(KafkaMessageChannelBinder.java:121)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:148)
	at org.springframework.cloud.stream.binding.ChannelBindingService.bindProducer(ChannelBindingService.java:113)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:208)
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 common frames omitted

[pom.txt](https://github.com/spring-cloud/spring-cloud-stream-starters/files/468431/pom.txt)

**Comment by mbogoevici** [comment]
Hi @mnadelson,

I wonder if this isn't due a classpath conflict. I see that you have both Brixton.SR5 and Brooklyn.M1 as part of your dependency management - I suspect that the Brixton BOM overrides some of the Brooklyn dependencies (Brixton used Stream 1.0) - could you possibly try using Camden.RC1 and Brooklyn.RC1 instead? Or at least invert the order of the BOMs (Stream Brooklyn First, Cloud Brixton next) ?

**Comment by mnadelson** [comment]
Thanks.  It was a classpath issue.  Not the one that you mentioned but some other things that I had in my pom.  You can close this issue.  Thanks.

**Comment by SWEnthusiast** [comment]
@mnadelson I have similar error, can you please post here what changes fixed your issue?

**Comment by imisweet1** [comment]
How its fixed, please explain.

**Comment by sw-enthusiast** [comment]
@imisweet1 I wiped out folders inside .m2 and changed spring cloud version to Camden.SR3 instead of Brixton.SR7

**Comment by sampleref** [comment]
I too face the same problem, I made Scala and spark as below: scala-library:2.11.7 ; spark-core_2.11:2.1.0 ; spark-streaming_2.11:2.1.0 ; spark-streaming-kafka-0-8_2.11:2.1.0 ;  kafka_2.11 and issue is resolved now

**Comment by mbogoevici** [comment]
@sampleref Are you using Spring Cloud Stream ?
